### ISSUE TITLE
How to config?

### ISSUE THREAD

**Issue by webprogrammierer** [southcoastweb/SCWCookie#11]
How to config the script? Please provide examples for Google Analytics, Amazon Partnernet, Ebay Partnernetwork, Amazon Pay, ....  What exactly has to be written in config.ini?

**Comment by mylesduncanking** [comment]
Hi @webprogrammierer,

I have updated the config.example.ini with some detailed comments on how to configure it.

The class only works for Google Analytics, Tawk.to, Smartsupp and Hotjar currently however if you would like to add the ability for more please feel free to create a pull request or send me a copy of the code which will need to be embedded when the cookie is enabled.
