### ISSUE TITLE
Use gdpr-cookie with yii2

### ISSUE THREAD

**Issue by eafiontzi** [southcoastweb/SCWCookie#14]
Hello,

I was wondering if someone has ever used gdpr-cookie with an MVC frameworks such as yii2 or Laravel and where should the files be copied in that case.

Thanks a lot in advance

**Comment by AdminUI** [comment]
Hi, although we have nt designed as Laravel Package we are using on a laravel websites.
We just include the files in the Public directory and then within the main template include the files as you would for a static site, (as per instructions)
